### PR TITLE
capistrano v2: Use deploy:restart instead deploy:finalize_update 

### PR DESCRIPTION
**Pull request by kibitan**
Hi! I've found an issue while integrating whenever into capistrano v2, and I propose a solution.
1. with Bundler problem
   After https://github.com/javan/whenever/pull/227 merged, some people complained that `whenever command not found` raised up in the particular situation using with Bundler integrations.
   I've got the same problem, and I found this problem is caused accidentally. 
   
   Bundler adds the hook at [`before "deploy:finalize_update", "bundle:install"`](https://github.com/bundler/bundler/blob/master/lib%2Fbundler%2Fcapistrano.rb#L13) 
   this is the same point with Whenever. If you `require` Whenever before Bundler, this problem will coming up.
   
   To avoid this problem, it's better to change the hook point into different point with Bundler.
2.  with `deploy:migrations`
   `deploy:migrations` is supplied by [capistrano](https://github.com/capistrano/capistrano/blob/2.15.5/lib%2Fcapistrano%2Frecipes%2Fdeploy.rb#L448), and `update_code` will execute before `db:migrate`.
   when `whenever:update_crontab` set before   `deploy:finalize_update`, the new-cron has a possibility to execute updated-code with old-schema db because of its before `db:migrate` finished. certainly it's not expecting behavior.
   I checked the merged PR https://github.com/javan/whenever/pull/227, and I also read a discussion about this change. https://github.com/javan/whenever/commit/fba25d3341fb688a44a2c79c9d62888a2b21fd1a
   [his opinion @leehambley ](https://github.com/javan/whenever/commit/fba25d3341fb688a44a2c79c9d62888a2b21fd1a#commitcomment-1044083)  made sense, but with migrations deploy, it will cause a problem.

I've think of expecting behavior, I suppose the new-cron set time should be in restarting process. Because I suppose the new-cron will be expected  to run with new-released application.

Capistrano v2 is already legacy version, of course we should not use it, but upgrade it. Im on the process to upgrade our quite big application, and it take a bit time. I suppose a few but there are people those who with same situation or facing same problem.
thanks for your nice library.

### CODE REVIEW

**Comment by dsandstrom** [comment]
Thanks @ctokoro. I was able to deploy when using your branch.

**Comment by benlangfeld** [comment]
Would it be acceptable instead to hook into `after "deploy:updated"` the same way we do with Capistrano 3, about which I don't see any complaints?

**Comment by bragamat** [comment]
@kibitan  can you provide some update on this or @benlangfeld can we close this one out ? 😄

**Comment by kibitan** [comment]
thank you for the mention, I don't remember this, and it is already for the old capistrano version. i would suggest to close it from my side

**Pull request closed without merging**
