### PR TITLE
Make runner commands use bundle exec (if a Gemfile is present)

### PR DESCRIPTION
**Pull request by judithroth**
When whenever registers a runner command, it doesn’t use bundle exec in the resulting crontab. This may cause errors like this:
'gem_original_require': no such file to load -- bundler/setup (LoadError)

This patch makes whenever runner commands use "bundle exec" when there's a Gemfile present (which indicates use of bundler).

### CODE REVIEW

**Comment by ajsharp** [comment]
Bump

**Comment by benlangfeld** [comment]
Merged as https://github.com/javan/whenever/commit/9f3707615c654bd21211ca164ddc938eca3cba76. Thank you for the contribution @judithroth!

**Comment by javan** [comment]
I believe this will construct `bundle exec bin/rails runner` when both bundler and `bin/rails` are present, which makes using the `bin/rails` binstub redundant. I *think* it'll work fine, just making a note of it.

**Comment by benlangfeld** [comment]
It is indeed redundant @javan, but does work. I figured it was better to resolve the bug quickly, and then come up with a consistent answer to binstubs vs `bundle exec` at lower priority :)

**Comment by benlangfeld** [comment]
Also note some people having trouble executing their binstubs directly at https://github.com/javan/whenever/issues/555. We'll have to take that into account if we want to smooth this out.

**Pull request closed without merging**
