### PR TITLE
Allow specifying a timezone that :at parameters should be interpreted as

### PR DESCRIPTION
**Pull request by twalpole**
Allows using set :timzone, '<timezone>' in the configuration file to specify that times in :at should be interpreted as being in the specified timezone and then converted to localtime for writing to cron

### CODE REVIEW

**Comment by dannyyu92** [comment]
require 'active_support/all'

Allows @JamesCropcho 's fix to work for me.

**Comment by flatrocks** [comment]
I agree that it makes better sense for scheduled jobs use server time zone, not Rails time zone.

However it's unnecessarily confusing since there's no mention of this in the README, and the examples use Rails time helpers ```every 1.day, :at => '4:30 am' do``` to describe scheduling (sort of implying the times will be interpreted per usual Rails implementation.).

I suggest adding a one-liner to the README to say this is how it works.  (And an added benefit is that it might prevent more issues being opened on this same topic.)

**Comment by jankeesvw** [comment]
This is my `schedule.rb` which works around the timezone issue, my server is in UTC, my users in CET (with daylight saving time):

```ruby
require "tzinfo"

env :PATH, ENV["PATH"]

def local(time)
  TZInfo::Timezone.get("Europe/Amsterdam").local_to_utc(Time.parse(time))
end

every :sunday, at: local("7:00 am") do
  rake "make:stuff:happen"
end

every 1.day, at: "1:00 am" do
  command "whenever --update-crontab"
end

**Comment by nathantsoi** [comment]
nice @jankeesvw, so basically put this somewhere in `schedule.rb`

```
require "tzinfo"
def local(time); TZInfo::Timezone.get("US/Pacific").local_to_utc(Time.parse(time)); end
```

then use:

```
every 1.hour, at: local('5:30 am') do
  # awesome things here
end
```

**Comment by jankeesvw** [comment]
Yes that should work @nathantsoi, but I would rather keep it readable though :sparkles:.

**Comment by iangreenleaf** [comment]
No disrespect to the folks who have kindly shared their solutions, they're certainly better than nothing, but they are really not sufficient for robust time zone support. Take, for example:

```ruby
require "tzinfo"
def local(time); TZInfo::Timezone.get("US/Pacific").local_to_utc(Time.parse(time)); end
every :sunday, at: local("10 pm") do
  # Start the week
end
```

This adjusts the *time* but not the *day* in cron:

```
0 5 * * 0 /bin/bash ...
```

Meaning it now runs at 5am Sunday UTC, which is 10pm **Saturday** Pacfic. Oops.

Sane time zone support really needs this gem's cooperation, or else a giant ugly monkey-patch to compensate for it.

**Comment by wbotelhos** [comment]
Using Rails, you can load the environment:

```
require File.expand_path('../config/environment', __dir__)
```

And than get the Rails zone:

```
every :day, at: Time.zone.parse('04:56am').localtime do
  runner 'My::Job.method'
end
```

**Pull request closed without merging**
