### PR TITLE
Added capability for updating cron without cmd

### PR DESCRIPTION
**Pull request by moskvin**
Need for dynamic updating crontab from code like this: `Whenever::update_cron`

### CODE REVIEW

**Comment by shterrett** [comment]
@moskvin 
:+1: 
It looks like your build failures are related to hash syntax; the build deps include ruby 1.8, so you need to go old school: `{ :key => val }`.

**Comment by moskvin** [comment]
I will fix it if you want)

**Comment by Kriechi** [comment]
@moskvin ping - any progress? I really like this feature!

**Comment by adisos** [comment]
@moskvin 
What's the status?

**Comment by bragamat** [comment]
@moskvin can you rebase your PR and make it mergeable ? 

cc @benlangfeld

**Comment by moskvin** [comment]
Let me check the PR

**Comment by moskvin** [comment]
done

**Comment by bragamat** [comment]
@benlangfeld still worth to merge it!

**Review by benlangfeld — APPROVED** [review]

**Pull request merged**
