### PR TITLE
fixing v3 cap includes

### PR DESCRIPTION
**Pull request by jramos**
The capistrano loader isn't working for v3. This fixes it.

### CODE REVIEW

**Comment by benlangfeld** [comment]
It is working for me. What makes you say it's not?

**Comment by jramos** [comment]
I get the following when using `cap-ec2`:

```
$ cap staging ec2:status
(Backtrace restricted to imported tasks)
cap aborted!
LoadError: cannot load such file -- /home/vagrant/.rvm/gems/ruby-2.2.2/gems/whenever-0.9.5/lib/whenever/tasks/whenever.rake
```

**Comment by benlangfeld** [comment]
You'll see that this is [a symlink](https://github.com/javan/whenever/blob/master/lib/whenever/tasks/whenever.rake). Are you running on some system that doesn't support symlinks? Could you check if the file is indeed present at all?

**Comment by jramos** [comment]
It's not there for me. Ubuntu 14.04.

```
$ ls -la /home/vagrant/.rvm/gems/ruby-2.2.2/gems/whenever-0.9.5/lib/whenever/tasks/
total 8
drwxrwxr-x 2 vagrant vagrant 4096 Jun 13 15:56 .
drwxrwxr-x 4 vagrant vagrant 4096 Jun 13 16:46 ..
$
```

**Comment by benlangfeld** [comment]
I've just checked, looks like this was a failure to build the gem. I'm looking into it.

**Comment by benlangfeld** [comment]
Released as 0.9.6. Apologies for the interruption in service.

**Comment by jramos** [comment]
Thanks for the quick fix!

**Pull request closed without merging**
