### PR TITLE
Make crontab command customizable

### PR DESCRIPTION
**Pull request by Grandrath**
To be able to update the correct crontab on my deploy server I like to be able to replace the crontab command with `sudo -u some-cronuser /usr/bin/crontab`. This PR adds the cli option `--crontab-command` which does just that. The default `crontab` command is unchanged.

### CODE REVIEW

**Comment by javan** [comment]
Would running `whenever` with sudo suffice?

**Comment by Grandrath** [comment]
@javan Running `whenever` with sudo would suffice but has an issue. I want to restrict sudo permissions as tight as possible. On the server I need to run `whenever` as `bundle exec whenever`. To only allow this specific call by sudo, I need to provide the absolute path to `bundle` in `/etc/sudoers`. This is not practical because this path looks like this: `/usr/local/rvm/gems/ruby-2.1.0/bin/bundle`. That means it changes when upgrading to a new Ruby version. In contrast allowing calls to `/usr/bin/crontab` is a lot simpler to manage.

**Comment by benlangfeld** [comment]
@p8 This needs a changelog entry and some explanation in the README. Once it has that I'll get it merged.

**Comment by p8** [comment]
@benlangfeld I've updated the Changelog and README https://github.com/javan/whenever/pull/677

**Comment by benlangfeld** [comment]
Merged in #677

**Pull request closed without merging**
